/**
 * Rich, realistic development & demo datasets for Pico's Dashboard.
 * Formatted to match the user's reference designs directly.
 */

import { Assessment, WorkItem, WorkOccurrence, Project, Task, UserProfile } from './types';

export const DEMO_USER_PROFILE: UserProfile = {
  uid: 'demo-user-pico',
  displayName: 'Pico',
  email: 'pico@example.com',
  avatarUrl: null,
  semesterConfig: {
    semesterName: 'August 2026',
    semesterStartDate: '2026-08-25', // Yields Academic Week 3 in September
  },
};

export const DEMO_TEAM_MEMBERS: Record<string, UserProfile> = {
  'demo-user-pico': { uid: 'demo-user-pico', displayName: 'Pico', email: 'pico@example.com', avatarUrl: null },
  'demo-user-alyssa': { uid: 'demo-user-alyssa', displayName: 'Alyssa', email: 'alyssa@example.com', avatarUrl: null },
  'demo-user-wayne': { uid: 'demo-user-wayne', displayName: 'Wayne', email: 'wayne@example.com', avatarUrl: null },
  'demo-user-jacob': { uid: 'demo-user-jacob', displayName: 'Jacob', email: 'jacob@example.com', avatarUrl: null },
};

// HOME TASKS (Main Quest, Things To Do, Done Today)
export const DEMO_HOME_TASKS: Task[] = [
  {
    id: 'task-mq-1',
    ownerId: 'demo-user-pico',
    title: 'Finish DAX Challenge',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:00:00.000Z',
    dueDate: '2026-10-05',
    area: 'study',
    priority: 'mainQuest',
    showOnHome: true,
    parentType: 'assessment',
    parentId: 'demo-assign-dax',
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-mq-2',
    ownerId: 'demo-user-pico',
    title: 'Review CS Proposal presentation deck',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:00:30.000Z',
    dueDate: '2027-03-30',
    area: 'study',
    priority: 'mainQuest',
    showOnHome: true,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-mq-3',
    ownerId: 'demo-user-pico',
    title: 'Confirm suria competition schedule & logistics',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:00:45.000Z',
    dueDate: '2026-09-19',
    area: 'work',
    priority: 'mainQuest',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-todo-1',
    ownerId: 'demo-user-pico',
    title: 'CW lesson plan',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:01:00.000Z',
    dueDate: '2026-09-18',
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: 'work',
    parentId: 'demo-work-cw',
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-todo-2',
    ownerId: 'demo-user-pico',
    title: 'Apply for DSU',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:02:00.000Z',
    dueDate: '2026-09-20',
    area: 'personal',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-todo-3',
    ownerId: 'demo-user-pico',
    title: 'Upload Suria Competition results',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:03:00.000Z',
    dueDate: '2026-09-17',
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-todo-4',
    ownerId: 'demo-user-pico',
    title: 'DAX Challenge',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:04:00.000Z',
    dueDate: '2026-10-05',
    area: 'study',
    priority: 'normal',
    showOnHome: true,
    parentType: 'assessment',
    parentId: 'demo-assign-dax',
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-todo-5',
    ownerId: 'demo-user-pico',
    title: 'Plan next Sat FriendsWhoChess',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:05:00.000Z',
    dueDate: '2026-09-26',
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-todo-6',
    ownerId: 'demo-user-pico',
    title: 'Plan CocoDay event',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:06:00.000Z',
    dueDate: '2026-09-22',
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-todo-7',
    ownerId: 'demo-user-pico',
    title: 'Continue finishing the system',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:07:00.000Z',
    dueDate: null,
    area: 'project',
    priority: 'normal',
    showOnHome: true,
    parentType: 'project',
    parentId: 'demo-proj-bingo',
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-todo-8',
    ownerId: 'demo-user-pico',
    title: 'Chess sales tracker',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:08:00.000Z',
    dueDate: null,
    area: 'project',
    priority: 'normal',
    showOnHome: true,
    parentType: 'project',
    parentId: 'demo-proj-sales',
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-todo-9',
    ownerId: 'demo-user-pico',
    title: 'Capstone project',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-15T08:09:00.000Z',
    dueDate: '2026-11-30',
    area: 'study',
    priority: 'normal',
    showOnHome: true,
    parentType: 'assessment',
    parentId: 'demo-assign-final',
    assignedToUserIds: ['demo-user-pico'],
  },

  // DONE TODAY (22 completed tasks to thoroughly verify fixed-height scrolling container)
  {
    id: 'task-done-1',
    ownerId: 'demo-user-pico',
    title: 'Reply to chess parent regarding weekend schedule',
    completed: true,
    completedAt: '2026-09-15T09:15:00.000Z',
    createdAt: '2026-09-15T07:30:00.000Z',
    dueDate: null,
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-2',
    ownerId: 'demo-user-pico',
    title: 'Submit tutorial 3 exercises for CSC1215',
    completed: true,
    completedAt: '2026-09-15T11:40:00.000Z',
    createdAt: '2026-09-15T07:35:00.000Z',
    dueDate: '2026-09-15',
    area: 'study',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-3',
    ownerId: 'demo-user-pico',
    title: 'Morning stretch & gym workout session',
    completed: true,
    completedAt: '2026-09-15T14:10:00.000Z',
    createdAt: '2026-09-15T07:40:00.000Z',
    dueDate: null,
    area: 'personal',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-4',
    ownerId: 'demo-user-pico',
    title: 'Review Joshua tactics homework batch',
    completed: true,
    completedAt: '2026-09-15T14:35:00.000Z',
    createdAt: '2026-09-15T07:45:00.000Z',
    dueDate: null,
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-5',
    ownerId: 'demo-user-pico',
    title: 'Download and verify CS301 syllabus slide deck',
    completed: true,
    completedAt: '2026-09-15T15:02:00.000Z',
    createdAt: '2026-09-15T07:50:00.000Z',
    dueDate: null,
    area: 'study',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-6',
    ownerId: 'demo-user-pico',
    title: 'Brew fresh herbal chamomile tea',
    completed: true,
    completedAt: '2026-09-15T15:30:00.000Z',
    createdAt: '2026-09-15T08:00:00.000Z',
    dueDate: null,
    area: 'personal',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-7',
    ownerId: 'demo-user-pico',
    title: 'Export attendance report for Moses',
    completed: true,
    completedAt: '2026-09-15T15:45:00.000Z',
    createdAt: '2026-09-15T08:10:00.000Z',
    dueDate: null,
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-8',
    ownerId: 'demo-user-pico',
    title: 'Read chapter 2 on database normalization',
    completed: true,
    completedAt: '2026-09-15T16:10:00.000Z',
    createdAt: '2026-09-15T08:15:00.000Z',
    dueDate: null,
    area: 'study',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-9',
    ownerId: 'demo-user-pico',
    title: 'Organize study desk & clear paper notes',
    completed: true,
    completedAt: '2026-09-15T16:30:00.000Z',
    createdAt: '2026-09-15T08:20:00.000Z',
    dueDate: null,
    area: 'personal',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-10',
    ownerId: 'demo-user-pico',
    title: 'Check tournament entry fee deadlines',
    completed: true,
    completedAt: '2026-09-15T16:50:00.000Z',
    createdAt: '2026-09-15T08:25:00.000Z',
    dueDate: null,
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-11',
    ownerId: 'demo-user-pico',
    title: 'Draft team meeting agenda with Alyssa & Wayne',
    completed: true,
    completedAt: '2026-09-15T17:15:00.000Z',
    createdAt: '2026-09-15T08:30:00.000Z',
    dueDate: null,
    area: 'study',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-12',
    ownerId: 'demo-user-pico',
    title: 'Update Bingo Chess color swatch palette',
    completed: true,
    completedAt: '2026-09-15T17:35:00.000Z',
    createdAt: '2026-09-15T08:35:00.000Z',
    dueDate: null,
    area: 'project',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-13',
    ownerId: 'demo-user-pico',
    title: 'Send invoice for private coaching block',
    completed: true,
    completedAt: '2026-09-15T17:50:00.000Z',
    createdAt: '2026-09-15T08:40:00.000Z',
    dueDate: null,
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-14',
    ownerId: 'demo-user-pico',
    title: 'Summarize key points from Data Mining lecture',
    completed: true,
    completedAt: '2026-09-15T18:10:00.000Z',
    createdAt: '2026-09-15T08:45:00.000Z',
    dueDate: null,
    area: 'study',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-15',
    ownerId: 'demo-user-pico',
    title: 'Back up local Git repository to remote',
    completed: true,
    completedAt: '2026-09-15T18:30:00.000Z',
    createdAt: '2026-09-15T08:50:00.000Z',
    dueDate: null,
    area: 'project',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-16',
    ownerId: 'demo-user-pico',
    title: 'Water the ivy window plants',
    completed: true,
    completedAt: '2026-09-15T18:45:00.000Z',
    createdAt: '2026-09-15T08:55:00.000Z',
    dueDate: null,
    area: 'personal',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-17',
    ownerId: 'demo-user-pico',
    title: 'Confirm classroom reservation for Saturday class',
    completed: true,
    completedAt: '2026-09-15T19:00:00.000Z',
    createdAt: '2026-09-15T09:00:00.000Z',
    dueDate: null,
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-18',
    ownerId: 'demo-user-pico',
    title: 'Set up DAX test environment and mock table',
    completed: true,
    completedAt: '2026-09-15T19:15:00.000Z',
    createdAt: '2026-09-15T09:05:00.000Z',
    dueDate: null,
    area: 'study',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-19',
    ownerId: 'demo-user-pico',
    title: 'Review Sicilian defense master game for Saturday',
    completed: true,
    completedAt: '2026-09-15T19:30:00.000Z',
    createdAt: '2026-09-15T09:10:00.000Z',
    dueDate: null,
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-20',
    ownerId: 'demo-user-pico',
    title: 'Sync calendar with phone notifications',
    completed: true,
    completedAt: '2026-09-15T19:45:00.000Z',
    createdAt: '2026-09-15T09:15:00.000Z',
    dueDate: null,
    area: 'personal',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-21',
    ownerId: 'demo-user-pico',
    title: 'Draft weekly reflection notes',
    completed: true,
    completedAt: '2026-09-15T20:00:00.000Z',
    createdAt: '2026-09-15T09:20:00.000Z',
    dueDate: null,
    area: 'personal',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'task-done-22',
    ownerId: 'demo-user-pico',
    title: 'Check overnight chess pairing notifications',
    completed: true,
    completedAt: '2026-09-15T20:15:00.000Z',
    createdAt: '2026-09-15T09:25:00.000Z',
    dueDate: null,
    area: 'work',
    priority: 'normal',
    showOnHome: true,
    parentType: null,
    parentId: null,
    assignedToUserIds: ['demo-user-pico'],
  },
];

// STUDY ASSESSMENTS
export const DEMO_ASSESSMENTS: Assessment[] = [
  // Upcoming Tests (8 tests)
  {
    id: 'demo-test-1',
    ownerId: 'demo-user-pico',
    name: 'Web Computing Test',
    courseCode: 'CSC1215',
    type: 'test',
    week: 2,
    date: '2026-09-15',
    weight: 20,
    status: 'Upcoming',
    pinned: true,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-test-2',
    ownerId: 'demo-user-pico',
    name: 'Data Mining Quiz',
    courseCode: 'CSDM2203',
    type: 'test',
    week: 4,
    date: '2026-09-24',
    weight: 10,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-test-3',
    ownerId: 'demo-user-pico',
    name: 'Database Systems Test',
    courseCode: 'CSDB2104',
    type: 'test',
    week: 5,
    date: '2026-10-01',
    weight: 15,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-test-4',
    ownerId: 'demo-user-pico',
    name: 'Discrete Mathematics Midterm',
    courseCode: 'MATH1102',
    type: 'test',
    week: 6,
    date: '2026-10-08',
    weight: 25,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-test-5',
    ownerId: 'demo-user-pico',
    name: 'Algorithms & Complexity Quiz 1',
    courseCode: 'CS302',
    type: 'test',
    week: 7,
    date: '2026-10-15',
    weight: 10,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-test-6',
    ownerId: 'demo-user-pico',
    name: 'Computer Architecture Quiz',
    courseCode: 'CSC2010',
    type: 'test',
    week: 9,
    date: '2026-10-27',
    weight: 15,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-test-7',
    ownerId: 'demo-user-pico',
    name: 'Operating Systems Midterm',
    courseCode: 'CSOS3100',
    type: 'test',
    week: 10,
    date: '2026-11-03',
    weight: 20,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-test-8',
    ownerId: 'demo-user-pico',
    name: 'Data Structures Final Exam',
    courseCode: 'CSDS2020',
    type: 'test',
    week: 14,
    date: '2026-12-01',
    weight: 40,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },

  // Upcoming Assignments (10 assignments)
  {
    id: 'demo-assign-web',
    ownerId: 'demo-user-pico',
    name: 'Web Development',
    courseCode: 'CSC1215',
    type: 'assignment',
    week: 8,
    date: '2026-10-19',
    weight: 25,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-assign-dax',
    ownerId: 'demo-user-pico',
    name: 'DAX Challenge',
    courseCode: 'CSDA2101',
    type: 'assignment',
    week: 6,
    date: '2026-10-05',
    weight: 25,
    status: 'In progress',
    pinned: true,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-assign-final',
    ownerId: 'demo-user-pico',
    name: 'Final Project',
    courseCode: 'CSC1215',
    type: 'assignment',
    week: 14,
    date: '2026-11-30',
    weight: 30,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: true,
    collaborationCode: 'KJQTX',
    memberIds: ['demo-user-pico', 'demo-user-alyssa'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-assessment-cs-proposal',
    ownerId: 'demo-user-pico',
    name: 'CS Project Proposal',
    courseCode: 'CS301 – Software Engineering',
    type: 'assignment',
    week: 7,
    date: '2027-03-30',
    weight: 20,
    status: 'In progress',
    pinned: true,
    collaborationEnabled: true,
    collaborationCode: 'KJQTX',
    memberIds: ['demo-user-pico', 'demo-user-alyssa', 'demo-user-wayne', 'demo-user-jacob'],
    createdAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'demo-assign-db-design',
    ownerId: 'demo-user-pico',
    name: 'Relational Schema & Normalization',
    courseCode: 'CSDB2104',
    type: 'assignment',
    week: 5,
    date: '2026-10-02',
    weight: 15,
    status: 'In progress',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-assign-mining-lab',
    ownerId: 'demo-user-pico',
    name: 'Clustering & Decision Tree Notebook',
    courseCode: 'CSDM2203',
    type: 'assignment',
    week: 7,
    date: '2026-10-14',
    weight: 20,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-assign-math-pset',
    ownerId: 'demo-user-pico',
    name: 'Combinatorics Problem Set',
    courseCode: 'MATH1102',
    type: 'assignment',
    week: 4,
    date: '2026-09-25',
    weight: 10,
    status: 'Completed',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-assign-os-shell',
    ownerId: 'demo-user-pico',
    name: 'Unix Shell & Pipe Implementation',
    courseCode: 'CSOS3100',
    type: 'assignment',
    week: 11,
    date: '2026-11-10',
    weight: 25,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: true,
    collaborationCode: 'OS310-PIPE',
    memberIds: ['demo-user-pico', 'demo-user-wayne'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-assign-algo-report',
    ownerId: 'demo-user-pico',
    name: 'Graph Traversal Complexity Report',
    courseCode: 'CS302',
    type: 'assignment',
    week: 9,
    date: '2026-10-29',
    weight: 20,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: false,
    collaborationCode: null,
    memberIds: ['demo-user-pico'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'demo-assign-ui-prototype',
    ownerId: 'demo-user-pico',
    name: 'Accessible UI Prototype & User Study',
    courseCode: 'CS301 – Software Engineering',
    type: 'assignment',
    week: 12,
    date: '2026-11-18',
    weight: 20,
    status: 'Upcoming',
    pinned: false,
    collaborationEnabled: true,
    collaborationCode: 'UIUX-PRO',
    memberIds: ['demo-user-pico', 'demo-user-alyssa', 'demo-user-jacob'],
    createdAt: '2026-08-28T00:00:00.000Z',
  },
];

// EXPANDED ASSESSMENT DETAILED DATA (CS Project Proposal)
export const DEMO_CS_PROPOSAL_TASKS: Task[] = [
  {
    id: 'csp-t1',
    ownerId: 'demo-user-pico',
    title: 'Read project brief & mark deliverables',
    completed: true,
    completedAt: '2026-03-11T10:00:00.000Z',
    createdAt: '2026-03-10T09:00:00.000Z',
    dueDate: '2027-03-30',
    area: 'study',
    priority: 'normal',
    showOnHome: false,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'csp-t2',
    ownerId: 'demo-user-pico',
    title: 'Brainstorm core product ideas with team',
    completed: true,
    completedAt: '2026-03-13T15:00:00.000Z',
    createdAt: '2026-03-10T09:00:00.000Z',
    dueDate: '2027-03-30',
    area: 'study',
    priority: 'normal',
    showOnHome: false,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-pico', 'demo-user-alyssa', 'demo-user-wayne', 'demo-user-jacob'],
  },
  {
    id: 'csp-t3',
    ownerId: 'demo-user-pico',
    title: 'Finalize architectural tech stack and diagram',
    completed: true,
    completedAt: '2026-03-16T11:00:00.000Z',
    createdAt: '2026-03-10T09:00:00.000Z',
    dueDate: '2027-03-30',
    area: 'study',
    priority: 'normal',
    showOnHome: true,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-pico', 'demo-user-alyssa', 'demo-user-wayne', 'demo-user-jacob'],
  },
  {
    id: 'csp-t4',
    ownerId: 'demo-user-pico',
    title: 'Draft problem statement & target personas',
    completed: false,
    completedAt: null,
    createdAt: '2026-03-10T09:00:00.000Z',
    dueDate: '2027-03-30',
    area: 'study',
    priority: 'normal',
    showOnHome: false,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-wayne'],
  },
  {
    id: 'csp-t5',
    ownerId: 'demo-user-pico',
    title: 'Write technical methodology & milestones',
    completed: false,
    completedAt: null,
    createdAt: '2026-03-10T09:00:00.000Z',
    dueDate: '2027-03-30',
    area: 'study',
    priority: 'normal',
    showOnHome: false,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-alyssa'],
  },
  {
    id: 'csp-t6',
    ownerId: 'demo-user-pico',
    title: 'Prepare database ER diagram & schema tables',
    completed: false,
    completedAt: null,
    createdAt: '2026-03-10T09:00:00.000Z',
    dueDate: '2027-03-30',
    area: 'study',
    priority: 'normal',
    showOnHome: false,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-jacob'],
  },
  {
    id: 'csp-t7',
    ownerId: 'demo-user-pico',
    title: 'Create Figma wireframes and visual mockups',
    completed: false,
    completedAt: null,
    createdAt: '2026-03-10T09:00:00.000Z',
    dueDate: '2027-03-30',
    area: 'study',
    priority: 'normal',
    showOnHome: false,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-pico', 'demo-user-alyssa'],
  },
  {
    id: 'csp-t8',
    ownerId: 'demo-user-pico',
    title: 'Review proposal rubrics against professor checklist',
    completed: false,
    completedAt: null,
    createdAt: '2026-03-10T09:00:00.000Z',
    dueDate: '2027-03-30',
    area: 'study',
    priority: 'normal',
    showOnHome: false,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-wayne', 'demo-user-jacob'],
  },
  {
    id: 'csp-t9',
    ownerId: 'demo-user-pico',
    title: 'Proofread and check APA formatting citations',
    completed: false,
    completedAt: null,
    createdAt: '2026-03-10T09:00:00.000Z',
    dueDate: '2027-03-30',
    area: 'study',
    priority: 'normal',
    showOnHome: false,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-alyssa'],
  },
  {
    id: 'csp-t10',
    ownerId: 'demo-user-pico',
    title: 'Compile final PDF and submit to portal',
    completed: false,
    completedAt: null,
    createdAt: '2026-03-10T09:00:00.000Z',
    dueDate: '2027-03-30',
    area: 'study',
    priority: 'normal',
    showOnHome: false,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'csp-t11',
    ownerId: 'demo-user-pico',
    title: 'Prepare 5-minute presentation slides',
    completed: false,
    completedAt: null,
    createdAt: '2026-03-10T09:00:00.000Z',
    dueDate: '2027-04-02',
    area: 'study',
    priority: 'normal',
    showOnHome: false,
    parentType: 'assessment',
    parentId: 'demo-assessment-cs-proposal',
    assignedToUserIds: ['demo-user-pico', 'demo-user-alyssa', 'demo-user-wayne', 'demo-user-jacob'],
  },
];

// 16 DATED NOTES for CS Project Proposal to test fixed-height scroll container
export const DEMO_CS_PROPOSAL_NOTES = [
  {
    id: 'note-1',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 10, 2027',
    items: [
      'Read through project brief and professor expectations',
      'Identified key requirements: must have real persistence & collaboration',
      'Initial concept: personal student study planner & companion',
    ],
    authorId: 'demo-user-pico',
    createdAt: '2027-03-10T10:00:00Z',
  },
  {
    id: 'note-2',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 12, 2027',
    items: [
      'Team kick-off sync with Alyssa, Wayne, and Jacob',
      'Agreed on Next.js 15, TypeScript, Tailwind CSS, and Firebase stack',
      'Assigned lead responsibilities for data model and UI design',
    ],
    authorId: 'demo-user-alyssa',
    createdAt: '2027-03-12T14:00:00Z',
  },
  {
    id: 'note-3',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 14, 2027',
    items: [
      'Researched similar productivity and Notion-like personal dashboards',
      'Created refined feature list and cozy visual archetype',
    ],
    authorId: 'demo-user-wayne',
    createdAt: '2027-03-14T16:00:00Z',
  },
  {
    id: 'note-4',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 15, 2027',
    items: [
      'Drafted initial data models for Tasks, Assessments, and Work Occurrences',
      'Verified Spark plan compatibility and eliminated need for heavy cloud functions',
    ],
    authorId: 'demo-user-jacob',
    createdAt: '2027-03-15T11:00:00Z',
  },
  {
    id: 'note-5',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 16, 2027',
    items: [
      'Pico sketched first window sill banner with sleeping fox and teacup',
      'Team approved warm neutral palette (#faf6ef and espresso text)',
    ],
    authorId: 'demo-user-pico',
    createdAt: '2027-03-16T15:30:00Z',
  },
  {
    id: 'note-6',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 17, 2027',
    items: [
      'Completed section 2: system architecture diagram',
      'Wayne tested Firebase Firestore rules for secure invite code mapping',
    ],
    authorId: 'demo-user-wayne',
    createdAt: '2027-03-17T18:00:00Z',
  },
  {
    id: 'note-7',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 19, 2027',
    items: [
      'Drafted section 3: functional user stories and acceptance criteria',
      'Alyssa added user flow diagrams for group assessment invitations',
    ],
    authorId: 'demo-user-alyssa',
    createdAt: '2027-03-19T13:15:00Z',
  },
  {
    id: 'note-8',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 20, 2027',
    items: [
      'Jacob outlined the weekly recurring work occurrences logic',
      'Verified single-week exception handling without mutating base series',
    ],
    authorId: 'demo-user-jacob',
    createdAt: '2027-03-20T17:00:00Z',
  },
  {
    id: 'note-9',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 21, 2027',
    items: [
      'Mid-sprint checkpoint meeting; all team members on schedule',
      'Refined Main Quest priority drag-and-drop mechanism specifications',
    ],
    authorId: 'demo-user-pico',
    createdAt: '2027-03-21T19:00:00Z',
  },
  {
    id: 'note-10',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 22, 2027',
    items: [
      'Added section on security and privacy controls',
      'Ensured Firestore rule blocks open collection queries on collaboration codes',
    ],
    authorId: 'demo-user-wayne',
    createdAt: '2027-03-22T14:40:00Z',
  },
  {
    id: 'note-11',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 24, 2027',
    items: [
      'Completed rough draft of sections 1 through 5',
      'Sent draft to TA for early preliminary feedback',
    ],
    authorId: 'demo-user-alyssa',
    createdAt: '2027-03-24T16:20:00Z',
  },
  {
    id: 'note-12',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 25, 2027',
    items: [
      'TA feedback received: positive on scope, recommended expanding on testing suite',
      'Jacob added unit testing matrix and end-to-end integration test plan',
    ],
    authorId: 'demo-user-jacob',
    createdAt: '2027-03-25T11:45:00Z',
  },
  {
    id: 'note-13',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 26, 2027',
    items: [
      'Integrated references and academic bibliography',
      'Checked document styling and verified contrast ratios for accessibility',
    ],
    authorId: 'demo-user-pico',
    createdAt: '2027-03-26T20:10:00Z',
  },
  {
    id: 'note-14',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 27, 2027',
    items: [
      'Proofreading round 1: corrected typographic inconsistencies',
      'Finalized Gantt chart schedule for 12-week development sprint',
    ],
    authorId: 'demo-user-wayne',
    createdAt: '2027-03-27T15:00:00Z',
  },
  {
    id: 'note-15',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 28, 2027',
    items: [
      'Proofreading round 2: final copy-editing and polish',
      'All 4 group members signed off on submission draft',
    ],
    authorId: 'demo-user-alyssa',
    createdAt: '2027-03-28T18:30:00Z',
  },
  {
    id: 'note-16',
    assessmentId: 'demo-assessment-cs-proposal',
    date: 'Mar 29, 2027',
    items: [
      'Generated high-res PDF with embedded vector illustrations',
      'Ready for portal upload tomorrow morning',
    ],
    authorId: 'demo-user-pico',
    createdAt: '2027-03-29T21:00:00Z',
  },
];

export const DEMO_CS_PROPOSAL_RESOURCES = [
  {
    id: 'res-1',
    assessmentId: 'demo-assessment-cs-proposal',
    title: 'Project Brief.pdf',
    url: '#',
    type: 'document' as const,
  },
  {
    id: 'res-2',
    assessmentId: 'demo-assessment-cs-proposal',
    title: 'Example Proposal.pdf',
    url: '#',
    type: 'document' as const,
  },
  {
    id: 'res-3',
    assessmentId: 'demo-assessment-cs-proposal',
    title: 'Proposal Writing Guide',
    url: '#',
    type: 'link' as const,
  },
  {
    id: 'res-4',
    assessmentId: 'demo-assessment-cs-proposal',
    title: 'CSC301 Lecture Notes',
    url: '#',
    type: 'document' as const,
  },
];

// WORK CALENDAR (SEPTEMBER 2026 DEMO DATA)
export interface CalendarEntryDemo {
  id: string;
  date: string; // YYYY-MM-DD
  dayNum: number;
  time: string;
  title: string;
  type: 'class' | 'event';
  workItemId: string;
  color?: 'sage' | 'blush' | 'lavender' | 'sand' | 'blue' | 'soft blue' | 'peach';
  recurrenceRule?: string;
  notes?: string;
}

export const DEMO_SEPTEMBER_ENTRIES: CalendarEntryDemo[] = [
  { id: 'entry-1-1', date: '2026-09-01', dayNum: 1, time: '4:00 PM – 5:00 PM', title: 'Joshua Private', type: 'class', workItemId: 'work-joshua', color: 'sage', recurrenceRule: 'Repeats weekly on Tuesday' },
  { id: 'entry-2-1', date: '2026-09-02', dayNum: 2, time: '5:00 PM – 6:00 PM', title: 'Curriculum Planning', type: 'event', workItemId: 'work-curriculum', color: 'lavender' },
  { id: 'entry-3-1', date: '2026-09-03', dayNum: 3, time: '4:00 PM – 5:00 PM', title: 'Moses Tactics', type: 'class', workItemId: 'work-moses', color: 'sage', recurrenceRule: 'Repeats weekly on Thursday' },
  { id: 'entry-4-1', date: '2026-09-04', dayNum: 4, time: '3:30 PM – 4:30 PM', title: 'Suria Organizer Sync', type: 'event', workItemId: 'work-suria-sync', color: 'peach' },
  { id: 'entry-5-1', date: '2026-09-05', dayNum: 5, time: '10:00 AM – 11:30 AM', title: 'Saturday Group Class', type: 'class', workItemId: 'work-group', color: 'sage', recurrenceRule: 'Repeats weekly on Saturday' },
  { id: 'entry-6-1', date: '2026-09-06', dayNum: 6, time: '12:00 PM – 1:00 PM', title: 'Joshua Class Journal', type: 'class', workItemId: 'work-joshua', color: 'sage', recurrenceRule: 'Repeats weekly on Sunday' },
  { id: 'entry-7-1', date: '2026-09-07', dayNum: 7, time: '7:00 PM – 8:00 PM', title: 'CocoDay Prep', type: 'event', workItemId: 'work-cocoday', color: 'blush' },
  { id: 'entry-8-1', date: '2026-09-08', dayNum: 8, time: '4:00 PM – 5:00 PM', title: 'Baxton Endgame', type: 'class', workItemId: 'work-baxton', color: 'sand', recurrenceRule: 'Repeats weekly on Tuesday' },
  { id: 'entry-10-1', date: '2026-09-10', dayNum: 10, time: '4:00 PM – 5:00 PM', title: 'Joshua Private', type: 'class', workItemId: 'work-joshua', color: 'sage', recurrenceRule: 'Repeats weekly on Thursday' },
  { id: 'entry-11-1', date: '2026-09-11', dayNum: 11, time: '6:30 PM – 7:30 PM', title: 'Arbiter Briefing', type: 'event', workItemId: 'work-arbiter', color: 'peach' },
  { id: 'entry-12-1', date: '2026-09-12', dayNum: 12, time: '10:00 AM – 11:30 AM', title: 'Saturday Group Class', type: 'class', workItemId: 'work-group', color: 'sage', recurrenceRule: 'Repeats weekly on Saturday' },
  { id: 'entry-14-1', date: '2026-09-14', dayNum: 14, time: '4:00 PM – 5:00 PM', title: 'Moses Tactics', type: 'class', workItemId: 'work-moses', color: 'sage', recurrenceRule: 'Repeats weekly on Monday' },

  // TUESDAY SEP 15 (BUSY DAY: 7 scheduled items to test 3 visible + 4 more)
  { id: 'entry-15-1', date: '2026-09-15', dayNum: 15, time: '9:00 AM – 10:00 AM', title: 'Morning Tactics Prep', type: 'class', workItemId: 'work-morning-tactics', color: 'sage' },
  { id: 'entry-15-2', date: '2026-09-15', dayNum: 15, time: '11:00 AM – 12:00 PM', title: 'Moses Private Check-in', type: 'class', workItemId: 'work-moses', color: 'sage', recurrenceRule: 'Repeats weekly on Tuesday' },
  { id: 'entry-15-3', date: '2026-09-15', dayNum: 15, time: '1:00 PM – 2:00 PM', title: 'Joshua Rapid Analysis', type: 'class', workItemId: 'work-joshua', color: 'sage', recurrenceRule: 'Repeats weekly on Tuesday' },
  { id: 'entry-15-4', date: '2026-09-15', dayNum: 15, time: '3:00 PM – 4:00 PM', title: 'Baxton Middlegame', type: 'class', workItemId: 'work-baxton', color: 'sand' },
  { id: 'entry-15-5', date: '2026-09-15', dayNum: 15, time: '4:30 PM – 5:30 PM', title: 'Suria Strategy Event', type: 'event', workItemId: 'work-suria', color: 'peach', recurrenceRule: 'Repeats weekly on Tuesday' },
  { id: 'entry-15-6', date: '2026-09-15', dayNum: 15, time: '6:00 PM – 7:00 PM', title: 'Curriculum Review', type: 'event', workItemId: 'work-curriculum', color: 'lavender' },
  { id: 'entry-15-7', date: '2026-09-15', dayNum: 15, time: '7:30 PM – 8:00 PM', title: 'Parent Consultation Call', type: 'event', workItemId: 'work-parent-call', color: 'soft blue' },

  { id: 'entry-16-1', date: '2026-09-16', dayNum: 16, time: '6:00 PM – 7:00 PM', title: 'Suria Competition Setup', type: 'event', workItemId: 'work-suria', color: 'blush' },
  { id: 'entry-18-1', date: '2026-09-18', dayNum: 18, time: '5:00 PM – 6:00 PM', title: 'Parent Consultation Call', type: 'event', workItemId: 'work-parent-call', color: 'soft blue' },
  { id: 'entry-19-1', date: '2026-09-19', dayNum: 19, time: '10:00 AM – 11:30 AM', title: 'Saturday Group Class', type: 'class', workItemId: 'work-group', color: 'sage', recurrenceRule: 'Repeats weekly on Saturday' },
  { id: 'entry-19-2', date: '2026-09-19', dayNum: 19, time: '2:30 PM – 4:00 PM', title: 'Blitz Challenge Session', type: 'event', workItemId: 'work-blitz', color: 'peach' },
  { id: 'entry-20-1', date: '2026-09-20', dayNum: 20, time: '12:00 PM – 1:00 PM', title: 'Joshua Lesson', type: 'class', workItemId: 'work-joshua', color: 'sage' },
  { id: 'entry-22-1', date: '2026-09-22', dayNum: 22, time: '4:00 PM – 5:00 PM', title: 'Joshua Tactics', type: 'class', workItemId: 'work-joshua', color: 'sage', recurrenceRule: 'Repeats weekly on Tuesday' },
  { id: 'entry-24-1', date: '2026-09-24', dayNum: 24, time: '4:00 PM – 5:00 PM', title: 'Baxton Endgame', type: 'class', workItemId: 'work-baxton', color: 'sand', recurrenceRule: 'Repeats weekly on Thursday' },
  { id: 'entry-25-1', date: '2026-09-25', dayNum: 25, time: '7:00 PM – 8:30 PM', title: 'FWC Tournament Setup', type: 'event', workItemId: 'work-fwc-setup', color: 'lavender' },
  { id: 'entry-26-1', date: '2026-09-26', dayNum: 26, time: '2:00 PM – 4:00 PM', title: 'FriendsWhoChess Meetup', type: 'event', workItemId: 'work-fwc', color: 'blush', recurrenceRule: 'Repeats weekly on Saturday' },
  { id: 'entry-28-1', date: '2026-09-28', dayNum: 28, time: '4:00 PM – 5:00 PM', title: 'Moses Final Prep', type: 'class', workItemId: 'work-moses', color: 'sage' },
  { id: 'entry-30-1', date: '2026-09-30', dayNum: 30, time: '4:00 PM – 5:00 PM', title: 'Joshua Lesson Review', type: 'class', workItemId: 'work-joshua', color: 'sage' },
];

// JOSHUA COACHING DIARY DEMO (Sep 6, 2026)
export const DEMO_JOSHUA_DIARY = {
  studentName: 'Joshua',
  subtitle: 'Sunday 12:00–1:00 • Class Journal',
  date: '2026-09-06',
  time: '12:00–1:00 PM',
  type: 'class' as const,
  subject: 'Chess Lesson',
  recurrenceRule: 'Repeats weekly on Sunday',
  color: 'sage' as const,
  whatHappened: [
    'mate in 3 warm up',
    'showed middlegame open-file ideas',
    'played one practice game',
    'discussed common mistakes',
    'quick puzzle challenge',
  ],
  nextLesson: [
    'review open-file concepts',
    'practice king-and-pawn ending',
    '5–10 min puzzles',
    'longer practice game',
  ],
  todoPrep: [
    { id: 'joshua-prep-1', title: 'prepare mate-in-3 puzzles', completed: true },
    { id: 'joshua-prep-2', title: 'set up practice position', completed: false },
    { id: 'joshua-prep-3', title: 'bring endgame examples', completed: false },
    { id: 'joshua-prep-4', title: 'review last lesson notes', completed: true },
  ],
  notesProgress:
    'Joshua was focused and asked good questions. He is improving at calculating lines but should slow down before making moves.',
};

// PROJECTS & IDEAS DEMO DATA (8 Active/Planning, 6 On Hold/Someday)
export const DEMO_PROJECTS: Project[] = [
  // Active Projects (8 projects)
  {
    id: 'demo-proj-bingo',
    ownerId: 'demo-user-pico',
    name: 'Bingo Space',
    description: 'student dashboard & attendance ideas',
    status: 'Active',
    section: 'active',
    icon: 'Target',
    targetDate: '2026-10-15',
    updatedAt: '2026-09-15T10:00:00.000Z',
    overviewNotes: 'Improve the student dashboard and attendance experience for Bingo Chess.',
    ideas: [
      'achievement system',
      'lesson summary after class',
      'coach feedback',
      'parent-friendly progress view',
    ],
    createdAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'demo-proj-sales',
    ownerId: 'demo-user-pico',
    name: 'Chess Sales Tracker',
    description: 'organize chess sales and records',
    status: 'Planning',
    section: 'active',
    icon: 'BarChart3',
    targetDate: '2026-10-31',
    updatedAt: '2026-09-14T14:30:00.000Z',
    overviewNotes: 'Track monthly lesson receipts, private coaching packages, and group session payouts.',
    ideas: [
      'automatic invoice generator',
      'student hours ledger',
      'yearly revenue chart',
    ],
    createdAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'demo-proj-study-hub',
    ownerId: 'demo-user-pico',
    name: 'Study Resources Hub',
    description: 'collect useful study links/tools',
    status: 'Active',
    section: 'active',
    icon: 'BookOpen',
    targetDate: '2026-11-05',
    updatedAt: '2026-09-13T09:15:00.000Z',
    overviewNotes: 'Central directory for CS notes, past papers, cheatsheets, and AI prompts.',
    ideas: [
      'tagging by subject code',
      'quick markdown preview',
      'bookmark sync',
    ],
    createdAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'demo-proj-engine',
    ownerId: 'demo-user-pico',
    name: 'PicoChess Engine',
    description: 'minimalist rust bitboard chess bot',
    status: 'Active',
    section: 'active',
    icon: 'Layers',
    targetDate: '2026-12-01',
    updatedAt: '2026-09-12T16:00:00.000Z',
    overviewNotes: 'Build a lightweight chess engine experimenting with alpha-beta pruning and magic bitboards.',
    ideas: [
      'magic bitboard move generation',
      'transposition table caching',
      'evaluation function tuning',
    ],
    createdAt: '2026-09-02T00:00:00.000Z',
  },
  {
    id: 'demo-proj-buddy',
    ownerId: 'demo-user-pico',
    name: 'AI Flashcard Buddy',
    description: 'auto-generate active recall cards from slides',
    status: 'Planning',
    section: 'active',
    icon: 'Sparkles',
    targetDate: '2026-11-20',
    updatedAt: '2026-09-11T12:00:00.000Z',
    overviewNotes: 'CLI tool parsing PDF lecture slides and generating spaced repetition markdown decks.',
    ideas: [
      'pdf extract to markdown',
      'spaced repetition intervals',
      'anki export support',
    ],
    createdAt: '2026-09-03T00:00:00.000Z',
  },
  {
    id: 'demo-proj-ledger',
    ownerId: 'demo-user-pico',
    name: 'Semester Ledger',
    description: 'track GPA calculations and assignment weights',
    status: 'Active',
    section: 'active',
    icon: 'FileText',
    targetDate: '2026-10-10',
    updatedAt: '2026-09-10T18:00:00.000Z',
    overviewNotes: 'Interactive spreadsheet calculator providing what-if scenarios for target GPAs.',
    ideas: [
      'target grade forecaster',
      'historical semester comparisons',
    ],
    createdAt: '2026-09-04T00:00:00.000Z',
  },
  {
    id: 'demo-proj-timer',
    ownerId: 'demo-user-pico',
    name: 'Tactics Speed Timer',
    description: 'chess puzzle countdown app with sound cues',
    status: 'Planning',
    section: 'active',
    icon: 'Lightbulb',
    targetDate: '2026-11-15',
    updatedAt: '2026-09-09T11:00:00.000Z',
    overviewNotes: 'Audio-guided tactical solve timer for students to build rapid intuition.',
    ideas: [
      'adaptive delay based on rating',
      'gentle audio chimes',
    ],
    createdAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'demo-proj-sync',
    ownerId: 'demo-user-pico',
    name: 'Obsidian Study Sync',
    description: 'sync university vault notes to dashboard',
    status: 'Active',
    section: 'active',
    icon: 'CheckCircle2',
    targetDate: '2026-10-25',
    updatedAt: '2026-09-08T15:00:00.000Z',
    overviewNotes: 'Sync daily notes and study reminders between local Obsidian vault and dashboard.',
    ideas: [
      'read frontmatter tags',
      'two-way checklist sync',
    ],
    createdAt: '2026-09-06T00:00:00.000Z',
  },

  // On Hold / Someday Maybe (6 projects)
  {
    id: 'demo-proj-website',
    ownerId: 'demo-user-pico',
    name: 'Personal Website',
    description: 'portfolio/blog with interactive chessboard',
    status: 'On Hold',
    section: 'someday',
    icon: 'Globe',
    targetDate: null,
    updatedAt: '2026-09-07T14:00:00.000Z',
    overviewNotes: 'Build a minimalist static portfolio sharing chess essays and coding experiments.',
    ideas: ['dark warm paper theme', 'interactive chessboard widget', 'reading list'],
    createdAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'demo-proj-mobile',
    ownerId: 'demo-user-pico',
    name: 'Mobile App Concept',
    description: 'study tools and timers on the go',
    status: 'Someday',
    section: 'someday',
    icon: 'Smartphone',
    targetDate: null,
    updatedAt: '2026-09-05T08:00:00.000Z',
    overviewNotes: 'Quick capture widget and study timer designed for iOS and Android.',
    ideas: ['lockscreen widget', 'quick note audio transcription'],
    createdAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'demo-proj-gym',
    ownerId: 'demo-user-pico',
    name: 'Gym Tracker',
    description: 'workout log & progressive overload tracker',
    status: 'Someday',
    section: 'someday',
    icon: 'Dumbbell',
    targetDate: null,
    updatedAt: '2026-09-04T19:00:00.000Z',
    overviewNotes: 'Simple 3-day split log with progressive overload tracking.',
    ideas: ['plate calculator', 'rest timer chime'],
    createdAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'demo-proj-player',
    ownerId: 'demo-user-pico',
    name: 'Cozy Lo-Fi Player',
    description: 'ambient rainy audio stream & study timer',
    status: 'Someday',
    section: 'someday',
    icon: 'Sparkles',
    targetDate: null,
    updatedAt: '2026-09-03T16:00:00.000Z',
    overviewNotes: 'Ambient rain synthesizer with vintage lofi chord generators for deep study.',
    ideas: ['rain frequency slider', 'soft brown noise'],
    createdAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'demo-proj-coffee',
    ownerId: 'demo-user-pico',
    name: 'Coffee Brewing Log',
    description: 'pour-over recipes and bean tasting notes',
    status: 'Someday',
    section: 'someday',
    icon: 'Target',
    targetDate: null,
    updatedAt: '2026-09-02T11:00:00.000Z',
    overviewNotes: 'Log grind settings, water temperature, brew ratios, and flavor notes.',
    ideas: ['bloom timer', 'flavor wheel selector'],
    createdAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'demo-proj-keyboard',
    ownerId: 'demo-user-pico',
    name: 'Custom Keyboard Firmware',
    description: 'ergonomic split keyboard keymap configs',
    status: 'Someday',
    section: 'someday',
    icon: 'Layers',
    targetDate: null,
    updatedAt: '2026-09-01T13:00:00.000Z',
    overviewNotes: 'QMK/ZMK firmware macros and shortcuts for fast coding navigation.',
    ideas: ['navigation thumb layer', 'chess PGN symbol macros'],
    createdAt: '2026-09-01T00:00:00.000Z',
  },
];

export const DEMO_BINGO_TASKS: Task[] = [
  {
    id: 'bingo-t1',
    ownerId: 'demo-user-pico',
    title: 'Improve student dashboard layout',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-12T00:00:00Z',
    dueDate: null,
    area: 'project',
    priority: 'normal',
    showOnHome: true,
    parentType: 'project',
    parentId: 'demo-proj-bingo',
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'bingo-t2',
    ownerId: 'demo-user-pico',
    title: 'Clean up attendance flow',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-12T00:00:00Z',
    dueDate: null,
    area: 'project',
    priority: 'normal',
    showOnHome: false,
    parentType: 'project',
    parentId: 'demo-proj-bingo',
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'bingo-t3',
    ownerId: 'demo-user-pico',
    title: 'Add progress tracking ideas',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-13T00:00:00Z',
    dueDate: null,
    area: 'project',
    priority: 'normal',
    showOnHome: false,
    parentType: 'project',
    parentId: 'demo-proj-bingo',
    assignedToUserIds: ['demo-user-pico'],
  },
  {
    id: 'bingo-t4',
    ownerId: 'demo-user-pico',
    title: 'Test mobile layout',
    completed: false,
    completedAt: null,
    createdAt: '2026-09-14T00:00:00Z',
    dueDate: null,
    area: 'project',
    priority: 'normal',
    showOnHome: false,
    parentType: 'project',
    parentId: 'demo-proj-bingo',
    assignedToUserIds: ['demo-user-pico'],
  },
];

export const DEMO_BINGO_NOTES = [
  'Sep 12: Wireframed the new student check-in card and test layout.',
  'Sep 14: Discussed parent notification flow with coaching team.',
  'Sep 15: Tested attendance toggle speeds on tablet; looking very clean.',
];
